# Background

Suicide is a worldwide leading cause of death in youth (Centers for Disease Control and Prevention, 2023; Curtin & Garnett, 2023; World Health Organization, 2025). Reductions in suicide could save numerous lives, and schools are a prevention setting that may be able to reach many young people (Ayer & Colpe, 2023). As interest-holders seek information on school-based suicide prevention, the existing research can be challenging to sift through, with extensive variation in study context and quality. This overview of systematic reviews synthesizes information from systematic reviews with meta-analysis on primary and secondary school-based suicide prevention. It also addresses issues with quality and risk of bias in suicide prevention systematic reviews. 

Suicide rates are high in young people. In 2021, suicide was the fourth leading cause of death globally in ages 15-19 (World Health Organization, 2025). In 2023, suicide was the second most common cause of death for ages 10-24 in the U.S. (Centers for Disease Control and Prevention, 2023). Research suggests that around 22 percent of U.S. middle schoolers surveyed in 2019 reported experiencing suicidal thoughts and 9 percent reported an attempt (Young et al., 2024). In some places, the problem has worsened over time. Between 2007 and 2018, U.S. suicide rates tripled for ages 10-14 and also increased for high school youth (Curtin & Garnett, 2023). Youth suicide rates increased further in the U.S., Japan, and a number of other countries when the covid-19 pandemic began (Bridge et al., 2023; Goto et al., 2022), although increases did not occur in all countries (Lantos & Nyári, 2024).  

Along with tragic loss of life, suicide and self-harm have other costs, including billions of dollars in annual medical expenses, reduced quality of life due to injuries, and workforce reductions (Peterson et al., 2024). Furthermore, “suicide contagion” can occur, where knowledge of a suicide or suicide attempt leads to increased suicides, attempts, and/or emotional distress in others (Mueller & Abrutyn, 2015; Shaman et al., 2024). Family members of people who attempt suicide are stressed in multiple ways (Sukmak et al., 2023; Vivekanandhan et al., 2025; Webb et al., 2025). Preventing suicide saves lives and also reduces additional economic harm and spread of mental health struggles to more people. 

Prevention in primary and secondary schools, especially universal prevention, may reach more youth and be more equitable than community-based services. Access barriers to mental health care, such as provider shortages, prohibitive financial costs, and stigma, may be less prevalent in schools than community settings (Ayer & Colpe, 2023). For suicide prevention in particular, support that does not rely on parents may be especially important, as research suggests that caregivers are often not aware when a child experiences suicidal ideation (Ayer & Colpe, 2023; DeVille et al., 2020). For the above reasons, some governments have ramped up school-based suicide prevention efforts, such as in the European Union (European Commission, 2017) and Japan (Matsumoto et al., 2024). Educators in the U.S. are also experiencing increased pressure from policymakers and the public to support student mental health in schools (American Foundation for Suicide Prevention, 2024).  

When considering school-based suicide prevention interventions, interest-holders need information on what works. Unfortunately, finding accessible, reliable, and specific information on K-12 school-based suicide prevention can be a challenge for education interest-holders. Primary studies often occur in a single geographical location or with a student demographic that may not be relevant for some interest-holders. A handful of systematic reviews with meta-analysis exist to provide a more comprehensive overview of this topic, but their scope and quality varies (see [Table 3](#sec-table3) and [Table 4](#sec-table4)). Some scientific journal articles are also paywalled or difficult to find. Even when interest-holders have access to the scientific literature, highly technical language and reporting methods used to communicate research results can be difficult to interpret (Baguley, 2009; Belia et al., 2005; Bullock et al., 2019; Gustafson & Rice, 2020). 

The goal of this overview of systematic reviews is to provide useful information for interest-holders from a variety of research and non-research backgrounds. We synthesize information from multiple systematic reviews and address issues with risk of bias and review quality.  
