

# Methods

This overview of systematic reviews was preregistered. The protocol and related materials are available on the Open Science Framework at <https://osf.io/4cqsw/overview> (Grant, Chinn, et al., 2025).  

## Eligibility Criteria 

We included systematic reviews with meta-analysis on effectiveness of K-12 school-based interventions for suicide prevention in students. Our eligibility criteria were based on the PICO framework (Eriksen & Frandsen, 2018) as well as considerations related to timing, setting, publication type, and design (see [Table 1](#sec-table1)). The restriction to English language publications was based on our team’s language abilities and resources. Treatment was defined as intervention after a suicide attempt (e.g., hospitalization) or prevention of a repeat suicide attempt. Postvention was defined as occurring after a suicide with the goal of preventing mental health issues in others. If a review included some eligible and some ineligible populations or settings according to our criteria, such as if a review included both K-12 and university settings, we included it if we determined that it provided information on K-12 school based suicide prevention interventions (e.g., if they conducted a K-12 subgroup analysis or a moderator analysis comparing K-12 to university settings). Grey literature was eligible (e.g., dissertations), but summary-only formats, such as conference abstracts, were not. 


## Search Strategy 

We followed the Campbell Collaboration guidance to develop the search strategy (MacDonald et al., 2024; Wilson et al., 2023) and provided a copy of the strategy on the Open Science Framework (<https://osf.io/b7dhj/>). We conducted a combined search to identify references for both this overview of reviews and our own systematic review. One author (KSF) created the search strategy. Two other authors (SG, LC) reviewed the strategy prior to execution using the Peer Review of Electronic Search Strategies (PRESS) Guideline (McGowan et al., 2016). We applied the PICO framework (Eriksen & Frandsen, 2018) to identify search terms related to each key concept matching our eligibility criteria: (1) school-based, (2) prevention, (3) methods, and (4) suicide. We used a combination of keywords and controlled vocabulary to create search strings specific to each bibliographic database. We employed two text-mining tools, PubMed PubReMiner and Yale MeSH Analyzer, to help identify frequent keywords, MeSH terms, and term variants (Grossetta Nardini & Wang, 2025; Koster, 2014). We ran a scoping search in PubMed and IN SUM (a database of systematic reviews on effects of child and adolescent mental health interventions) to identify potentially eligible publications. We then tested our search strings against the benchmark publications found in the scoping search. After the PRESS review, we added ‘pupil*’ keyword to all search strings and wildcards to account for UK spelling in several terms. We did not use published search hedges or database-specific filters. Neither did we apply any date, language, or document format restrictions in our searches. We used DistillerSR ‘Duplicate Detection’ feature to deduplicate our results (DistillerSR Inc., 2025). After our initial search in January 2025, we updated our search monthly in PubMed and quarterly in ProQuest through December 2025.  

 
## Information Sources 

We searched for eligible systematic reviews using the following bibliographic databases (with search platforms in parentheses): PubMed (National Library of Medicine), APA PsycINFO (APA PsycNet), ProQuest Dissertations & Theses Global (ProQuest), and Social Science Premium Collection (ProQuest). The Social Science Premium Collection includes the Criminology Collection, Education Collection (which includes Education Resources Information Center, or “ERIC”), International Bibliography of the Social Sciences, Library & Information Science Collection, Linguistics Collection, Politics Collection, Social Science Database, and Sociology Collection. We also searched the following sources: systematic review and trial registries (IN SUM, clinicaltrials.gov, and WHO International Clinical Trials Registry Platform), web search engines (Google Scholar), regional databases (Australian Education Index), and relevant government and non-government web sites. In addition, we used citationchaser to harvest references from eligible studies and for forward citation chasing. Finally, we hand searched the following journals: Discover Psychology, Mental Health & Prevention, and Revista de Psicodidáctica (English ed.). 

 
## Selection Process 

Citations were uploaded to DistillerSR software, and duplicates were merged using the “Duplicate Detection” feature. All titles and abstracts were screened in DistillerSR according to the eligibility criteria described above. To expedite screening, any report marked as eligible by one screener was retained. When a reference was marked as ineligible by one screener, it was independently screened by a second screener, such that references were only dropped if two screeners marked them ineligible. After screening decisions were made about references identified in the initial January 2025 search, the DistillerSR machine learning tool (DistillerAI) was trained on the team’s screening decisions. This tool assigns a confidence score of 0-1 that represents the likelihood that a reference would be retained by our screeners. We compared the confidence scores to our manual screening decisions from the screening round and identified thresholds to apply the AI tool. For additional search results, we set these thresholds to automatically exclude references with scores ≤ 0.1 and automatically include those with scores ≥ 0.9. References with scores between 0.1 and 0.3 were manually screened by one human team member to verify their exclusion status. References with scores ≥ 0.3 and < 0.9 were screened with the same process as the initial human screening round, where references were only dropped if two human coders marked them as ineligible. This approach follows recommendations to set thresholds based on AI performance on datasets with known decisions, versus applying formal stopping rules (Repke et al., 2026).  

Full texts were downloaded for each reference retained during title and abstract screening and were assessed by two authors. Disagreements were resolved by discussion between the two reviewers with input from a third member of the research team as necessary.  

## Data Collection 

Data collection, risk of bias, and quality ratings were completed by two independent coders. Discrepancies were resolved via discussion between the two coders, as well as consultation with a third team member when needed. Published updates of reviews were coded independently of initial reviews. Coding was done using forms designed in DistillerSR software. Coders extracted information including bibliographic information (e.g., author name and year), search strategy (e.g., last search date, databases searched), registration number, inclusion/exclusion criteria, sample sizes, and meta-analytic estimates for suicide outcomes. Each eligible systematic review was also given a Risk of Bias in Systematic Reviews rating (ROBIS; Whiting et al., 2016) and a quality rating with A MeaSurement Tool to Assess systematic Reviews–2 (AMSTAR-2; Shea et al., 2017).  

## Synthesis Methods 

We narratively report descriptive information for eligible systematic reviews. Next, we summarize overlap across systematic reviews with respect to their included studies. This overlap is illustrated in a citation matrix figure and quantified by Corrected Covered Area (CCA) calculations. Finally, we narratively summarize meta-analytic estimates from eligible systematic reviews with results organized according to PICO (population, intervention, comparison, outcome) categories. Results are discussed in terms of their variation across PICO categorie

