
```{r}
#| include: false

objs <- readRDS(here::here("outputs", "objects", "analysis_script_objects.rds"))
list2env(objs, envir = knitr::knit_global())

```

# Results

Our search yielded `r format_thousands(overview_counts$records_identified)` citations (see [Figure 1](#sec-figure1)). After removing duplicates, we screened `r format_thousands(overview_counts$records_screened)` records, retained `r format_thousands(overview_counts$records_kept)` records (`r format_percent(overview_counts$prop_kept, 1)`) for full-text eligibility assessment (not all were reviews), and were able to retrieve `r format_thousands(overview_counts$reports_assessed)` full-texts for eligibility assessment. Of the `r format_thousands(overview_counts$reports_assessed)` full-texts assessed, we identified `r format_thousands(overview_counts$reviews_included)` eligible systematic reviews with information reported across `r format_thousands(overview_counts$reports_included)` records (`r format_percent(overview_counts$prop_reviews_assessed, 1)` of full-texts assessed for eligibility; `r format_percent(overview_counts$prop_reviews_identified, 1)` of all citations identified in our search). [Appendix 1](#sec-appendix1) lists the reason for exclusion for each full-text assessed. See [Appendix 2](#sec-appendix2) for a list of reviews in which we are awaiting to hear more information from the corresponding author to determine eligibility. [Appendix 3](#sec-appendix3) contains detailed information on the `r format_thousands(overview_counts$reviews_included)` included systematic reviews.

## Included Systematic Review Characteristics

Reviews varied in their eligibility criteria. Two reviews included studies on effects of child and adolescent school-based prevention on suicide outcomes in children and/or adolescents (Gijzen et al., 2022; Walsh et al., 2022). These reviews included studies that tested effects of suicide-prevention interventions as well as broader intervention targets (e.g., mental health or suicide risk factors like depression) on suicide outcomes (Gijzen et al., 2022; Walsh et al., 2022). Three other reviews focused on prevention-interventions designed specifically for suicide but included older students (Brann et al., 2021; Kiran et al., 2024), did not have age-related eligibility criteria (Pistone et al., 2019), included interventions delivered to school staff (Brann et al., 2021; Kiran et al., 2024), and/or included interventions delivered outside of education settings (e.g., adult gatekeeper training in workplaces; Pistone et al., 2019). . No reviews explicitly excluded screening only programs.

Overall, these `r nrow(review_td)` reviews were published between `r min(review_td$review_publication_year)` and `r max(review_td$review_publication_year)`, with a median publication year of `r median(review_td$review_publication_year)` (see [Table 2](#sec-table2)). These reviews most commonly searched *APA PsycInfo* (`r mode_databases$num_db[1]` reviews; `r format_percent(mode_databases$percent[1], 1)`), *Cochrane Central Register of Controlled Trials* (`r mode_databases$num_db[2]` reviews; `r format_percent(mode_databases$percent[2], 1)`), *MEDLINE* (`r mode_databases$num_db[3]` reviews; `r format_percent(mode_databases$percent[3], 1)`), and *ERIC* (`r mode_databases$num_db[4]` reviews; `r format_percent(mode_databases$percent[4], 1)`) to identify primary studies. The year that each review last conducted their literature search ranged from `r min(review_df$db_search_year, na.rm = TRUE)` to `r max(review_df$db_search_year, na.rm = TRUE)`, with a median of `r ceiling(median(review_df$db_search_year, na.rm = TRUE))`. Regarding research transparency, `r num_prisma` reviews (`r format_percent(num_prisma / nrow(review_df) * 100, 1)`) included a flow diagram of information through the different phases of a systematic review (Page et al., 2021), `r num_reg` reviews (`r format_percent(num_reg / nrow(review_df) * 100, 1)`) reported a registration number for their review (Booth et al., 2012), and `r num_avail` reviews (`r format_percent(num_avail / nrow(review_df) *100, 1)`) provided statements about the data and code underlying the review (Page et al., 2022).

## Overlap Across Systematic Reviews

The number of primary studies included in each review ranged from `r min(df_overlap$num_stud)` to `r max(df_overlap$num_stud)`, with a median of `r round(median(df_overlap$num_stud))`. Of the `r nrow(td_cm)` primary studies included across all reviews, `r num_inc_overlap` studies (`r format_percent(num_inc_overlap_per, 1)`) were included in more than one review (see [Figure 2](#sec-figure2)). The overall CCA percentage for all primary studies included across reviews was `r format_percent(cca_included$CCA_Percentage, 1)`, indicating *high* overlap in primary studies across reviews. No single review identified all primary studies on school-based suicide prevention interventions.

## Critical Appraisal of Included Systematic Reviews

*Appendix 4 contains our critical appraisal assessments (i.e., ratings and rationale) for each item in both instruments across all included reviews. *

AMSTAR-2 assessments (see [Table 3](#sec-table3)) yielded methodological quality ratings of low for `r amstar_low` reviews (`r format_percent(amstar_low_per, 1)`) and critically low for `r amstar_clow` reviews (`r format_percent(amstar_clow_per, 1)`). The most common critical weaknesses in methodological quality were *not providing justification for excluding individual studies* (`r amstar_crit_mode$n[1]` reviews; `r format_percent(amstar_crit_mode$percent[1], 1)`), *not considering risk of bias when interpreting the results of the review* (`r amstar_crit_mode$n[2]` reviews; `r format_percent(amstar_crit_mode$percent[2], 1)`), and *not having a protocol registered before commencement of the review* (`r amstar_crit_mode$n[3]` reviews; `r format_percent(amstar_crit_mode$percent[3], 1)`). The most common non-critical weaknesses in methodological quality were *not reporting funding sources for included studies* (`r amstar_noncrit_mode$n[1]` reviews; `r format_percent(amstar_noncrit_mode$percent[1], 1)`), *not assessing the impact of risk of bias in individual studies on evidence synthesis results* (`r amstar_noncrit_mode$n[2]` reviews; `r format_percent(amstar_noncrit_mode$percent[2], 1)`), and *not explaining the selection criteria used to identify included study designs* (`r amstar_noncrit_mode$n[3]` reviews; `r format_percent(amstar_noncrit_mode$percent[3], 1)`).

ROBIS assessments (see [Table 4](#sec-table4)) yielded ratings of low risk of bias for `r robis_low` reviews (`r format_percent(robis_low_per, 1)`, unclear risk of bias for `r robis_unclear` review `r format_percent(robis_unclear_per, 1)`), and high risk of bias for `r robis_high` reviews (`r format_percent(robis_high_per, 1)`). Concerns about risk of bias were most commonly related to *study eligibility criteria* (`r robis_concerns$n_decision[1]` reviews; `r format_percent(robis_concerns$per_decision[1], 1)`), *identification and selection of studies* (`r robis_concerns$n_decision[2]` reviews; `r format_percent(robis_concerns$per_decision[2], 1)`), and *synthesis and findings* (`r robis_concerns$n_decision[3]` reviews; `r format_percent(robis_concerns$per_decision[3], 1)`).

## Review Findings

We identified meta-analytic estimates of suicide outcomes for school-based prevention interventions overall (Table 4), as well as for specific intervention approaches or contrasts (Table 5). Two reviews (Kiran et al. 2023 and Pistone et al. 2019) only reported moderator analyses but did not report overall effects of school-based suicide prevention interventions; consequently, they 
do not have results reported in *Table 4* and are reported in *Table 5*. 

### Overall Effects

Meta-analytic estimates reported here were derived mainly from primary studies described as meeting our inclusion/exclusion criteria. However, some analyses may have included a small number of primary studies not meeting our inclusion/exclusion criteria. Specifically, the Gijzen (2022) and Brann (2021) meta-analyses included a study with gatekeeper and screening intervention arms (Wasserman et al., 2015), but most studies in the analyses were reported as containing interventions delivered to students. Walsh et al. (2022) included a small number of screening or gatekeeper programs in their systematic review, but it is unclear if any or how many of these were included in the meta-analyses reported in this section. 
	
#### Suicidal behaviors
Gijzen and colleagues (2022) found that school-based prevention interventions were associated with fewer suicidal behaviors at 0-3 months post-test relative to no intervention, placebo, and usual care control groups (SMD = .30, 95% CI .15 to .45, p <.001). Heterogeneity was high (I2 = 94, 95% CI 90 to 96). The same review also found benefits at 3-12 months (SMD = 0.30, 95% CI 0.16 to 0.43, p <.001). Walsh and colleagues (2022) also found that interventions were associated with fewer suicide attempts relative to comparison groups at 0- to 20-month follow-ups (adjusted log OR = .72, 95% CI .59 to .87). This analysis had no significant heterogeneity (Q18 = 10.46, p = .49; within-study heterogeneity = 9.10%, between-study heterogeneity = 0%). Brann (2021) found a small effect indicating fewer suicidal behaviors for intervention relative to control groups in high school (SMD = .17, 95% CI .06 to .26, p < .01).

#### Suicidal ideation outcomes 
Gijzen and colleagues (2022) found a small benefit of school-based prevention interventions on suicidal ideation outcomes relative to no intervention, placebo, and usual care control groups at 0-3 months post-test (SMD = .15, 95% CI .06 to .24, p = .001, k = 10 effect sizes). Heterogeneity was high (I2 = 85, 95% CI 73 to 91). Walsh and colleagues (2022) examined all follow-up time points (0-20 months) and results suggested that school-based prevention interventions reduced suicidal ideation in adolescents relative to no intervention, other intervention, and waitlist control comparisons (adjusted log OR = .85, 95% CI .75 to .95). This analysis did not have significant heterogeneity (Q18 = 10.04, p = .93, within-study and between-study heterogeneity = 0.0%). 

### Effects of Intervention Approach

#### Targeting versus not targeting STBs
Two systematic reviews tested the effect of whether interventions primarily targeted suicidal thoughts and behaviors (STBs) versus interventions not designed specifically for STBs, such as those targeting risk factors for suicide or general mental health. Gijzen and colleagues (2022) found mixed results. For suicidal behaviors, they found that interventions primarily targeting STBs were less effective compared to those targeting risk factors (b = − 0.87, SEb = 0.28, z = − 3.04, 95% CI − 1.42 to − 0.31, p = .002), but those targeting STBs were still found to be beneficial (SMD = .23, p < .001). For suicidal ideation outcomes, a meta-regression indicated that interventions primarily targeting STBs did not produce significantly different effects than those targeting risk-factors (b = − 0.22, SEb = 0.15, z = − 1.49, 95% CI − 0.50 to − 0.07, p = .136). These results should be interpreted with caution due to inclusion of only one primary study that did not target STBs and high heterogeneity. Walsh and colleagues (2022) also conducted meta-regressions on effects of interventions primarily targeting STBs. They found that interventions primarily targeting STBs were associated with fewer suicide attempts relative to controls (adjusted log OR = .67, p <.001), but those not primarily targeting STBs showed no statistically significant benefits (adjusted log OR = 1.11; adjusted log OR for contrast = -.51 (95% CI -1.04 to .02)). 


#### Educational interventions
Pistone and colleagues (2019) focused on educational interventions, described as designed to help identify people at risk of suicide. In an analysis excluding gatekeeper trainings, they found that school-based education interventions were associated with fewer suicide attempts relative to comparison groups at 3-month follow up (OR = .56, 95% CI .39 to .80, p = .001, k = 3 studies) and 12-month follow-up (OR = .60, 95% CI .38 to .95, p = .03, k = 2 studies). A meta-analysis on suicidal ideation found no statistically significant benefit at 3-month follow-up (OR = .82, 95% CI .56 to 1.19, p = .29, k = 2 studies), but there was an observed benefit at 12-month follow-up (OR = .54, 95% CI .35 to .81, p = .003, k = 2 studies).

### Effect of School Level for Universal Prevention

Kiran and colleagues (2023) conducted a meta-regression comparing effects of school (middle-high school) versus college-level universal prevention targeting pupils/students on suicidality outcomes. Results indicated that intervention effectiveness did not significantly differ by school level (B = 0.178, 95% CI -1.116 to 1.471, p = .788). 
	
### Effect of Follow-Up Timing

Walsh and colleagues (2022) performed contrasts comparing suicide attempt outcomes at ≤ 3 months to 12- and 17-to 20-month follow-ups. Interventions groups had fewer suicide attempts than comparison groups at ≤ 3 months (adjusted log OR = .70, p < .01, k = 6 effects from 4 studies) and 12 months (adjusted log OR = .59, p < .01, k = 3 effects from 1 study), but not at 17 to 20 months (adjusted log OR = 1.06, k = 3 effects from 3 studies). However, neither contrast was statistically significant (12 months vs. ≤ 3 months log OR = -.16, 95% CI -.59 to .26; 17-20 months vs. ≤ 3 months log OR =.42, 95% CI -.11 to .95). As noted above, this review included some interventions not primarily targeting STBs, such as those targeting STB risk factors.



