
```{r}
#| include: false

objs <- readRDS(here::here("outputs", "objects", "analysis_script_objects.rds"))
list2env(objs, envir = knitr::knit_global())

```

# Discussion

We identified `r overview_counts$reviews_included` eligible systematic reviews that included `r nrow(td_cm)` primary studies across all reviews. Researchers conceptualized suicide prevention in multiple ways. For instance, some interventions aim to prevent suicide via risk factors such as depression or mental health, while others directly targeted STBs. Overall, results generally suggest that school-based suicide prevention programs have modest positive average effects on suicide-related outcomes. Two systematic reviews with meta-analyses of randomized trials found that school-based prevention interventions reduced both suicidal ideation and suicide attempts/behaviors relative to controls overall at short-term and longer-term follow-ups (Gijzen et al., 2022; Walsh et al., 2022). In addition, findings suggest several factors that may impact effectiveness. In terms of intervention approach, interventions primarily targeting STBs may reduce suicide attempts (Walsh et al., 2022). For suicidal behaviors more broadly, interventions targeting risk factors may produce larger effects than those primarily targeting STBs (Gijzen et al., 2022). Educational interventions designed to identify people at risk of suicide may yield fewer suicide attempts at both 3-month and 12-month follow-ups, with mixed evidence for effects on suicidal ideation (Pistone et al., 2019). In terms of student age and school level, one review did not detect differences between effects at the middle/high school level versus the college level for universal prevention targeting suicidality outcomes (Kiran et al., 2024). One review conducted an analysis specifically on high school populations and also detected a small benefit on suicidal behaviors (Brann et al., 2021). In terms of follow-up timing, evidence suggests fewer suicide attempts among intervention groups relative to comparison groups at shorter (≤ 3 months) and medium-term (12-month) follow-ups, but not at longer-term (17–20 month) follow-ups (Walsh et al., 2022). Given limitations in the current body of primary evidence on these interventions, future research is needed to improve confidence in these moderating factors.    

## Implications for Policy and Practice

	Taken together, the results summarized in this overview indicate that schools may be a promising setting for suicide prevention. Effect sizes across existing systematic reviews are small, but small effect sizes are common in youth mental health prevention research (Tanner-Smith et al., 2018). Since suicidality is a top contributor to youth mortality in many countries, the number of students who would potentially benefit from even modestly effective suicide prevention interventions in schools is substantial. Still, the evidence is uncertain, given some inconsistent results, low AMSTAR-2 quality ratings, high ROBIS risk of bias ratings, and author concerns about publication bias and quality of primary studies. Therefore, we suggest that interest-holders weigh potential benefits against practical factors such as resource constraints. When considering specific programs, interest-holders should also consider how well programs would fit in their local contexts (E. Day et al., 2025).
	
## Implications for Future Research

Our assessments of review quality and meta-analytic risk of bias suggest a new systematic review may be warranted to provide users of this evidence base with an up-to-date synthesis of the literature and to overcome methodological limitations of existing reviews. For instance, this review could address reasons for lower AMSTAR-2 and ROBIS ratings in most reviews, such as a prospectively registered protocol and analysis plan, a comprehensive search strategy (including gray literature and studies not published in English), incorporation of satisfactory tools for risk of bias assessment into syntheses, and use of formal approaches to rating and communicating certainty of evidence (Guyatt et al., 2008; Santesso et al., 2020). In addition, this systematic review could provide estimates of direct evidence: that is, suicide-focused prevention interventions (as current reviews often covered interventions not focused on suicide) and interventions delivered during the school day (as current reviews often combined evidence for interventions delivered during the school day with those delivered on school premises but outside of normal school hours). For example, some reviews included interventions not delivered directly to students, such as gatekeeper interventions for school staff, and review eligibility criteria did not usually specify intervention recipients. To address many of these needs, we plan to conduct a new, standalone, living systematic review on school-based suicide prevention interventions delivered to students during normal school hours, as part of a meta-analytic research domain (Cuijpers et al., 2022) on school-based mental health prevention programs. 

## Limitations and Future Directions

While this overview has several strengths, we note several limitations. First, our search may not have identified all eligible reviews. While we did not use language restrictions in our search strategy, we did not have proficiency in languages other than English on our review team. We also did not contact content experts and organizations for missing reviews nor search systematic review-specific repositories (e.g., Epistemonikos, KSR Evidence, PROSPERO, Cochrane Database of Systematic Reviews) for completed or ongoing reviews. Future updates to this overview can incorporate non-English publications, contact experts and organizations, and search review registries. Second, we did not contact systematic review authors to validate our methodological analysis or obtain missing information (Faggion et al., 2023). We also did not reassess reported information, reanalyze data to conduct our own meta-analyses and sensitivity analyses, or independently obtain desired information when missing. Third, we only collected information on the effects of interventions on suicide-related outcomes. Some reviews reported additional outcomes not originally in our protocol, such as improvements in suicide awareness and helping skills associated with intervention. Other types of evidence critical to the delivery of school-based suicide prevention interventions include equity, feasibility of implementation, acceptability to key interest-holders, intervention costs, cultural considerations, and adverse effects such as contagion and increased distress following exposure to suicide-related content (Abrutyn & Mueller, 2014; Shaman et al., 2024). Finally, we did not include supplemental primary studies in this overview, limiting the evidence in this article to that synthesized and reported in existing systematic reviews. We also did not examine and manage discrepant data (i.e., data from the same primary study reported differently across eligible systematic reviews) during data collection and analysis. Outcome definitions varied across the included reviews in ways we did not harmonize, and differences in measurement instruments, time frames, and rater types may contribute to heterogeneity in reported estimates and limit direct comparability across reviews. Our citation matrix was constructed at the primary study level and did not account for whether different reviews meta-analyzed the same or different effect sizes from within a primary study, which could lead to an overestimate of overlap relative to overlap at the meta-analytic level (Bracchiglione et al., 2026). 

## Conclusions

The goal of this overview was to synthesize systematic reviews with meta-analyses focused on the effects of suicide prevention interventions for primary and secondary students in school settings. School-based suicide prevention programs may yield modest yet possibly meaningful reductions in suicidal behaviors and ideation among primary and secondary school students on average. However, limitations in both the primary evidence and existing systematic reviews caution against conclusive recommendations, such as policies mandating suicide prevention interventions in schools. High-quality primary and secondary research is still needed to better understand the effects of suicide prevention interventions in schools. 
